name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # A etapa de testes agora é simplificada para usar o Docker Compose
      - name: Run tests with Docker
        run: docker compose up --build --abort-on-container-exit
      
      # Opcional: Upload do relatório se ele for gerado dentro do contêiner.
      # Para isso funcionar, precisaríamos de um volume no docker-compose.
      # Por enquanto, vamos manter o foco em fazer os testes passarem.